# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiebetaaltwat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='wbw_id',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
