from django.core.management.base import BaseCommand, CommandError
from orders.models import Item, Discount


class Command(BaseCommand):
    help = 'Populates the database with the Fest menu'

    def _add_item(self, name, price, *discounts):
        item = Item.objects.create(name=name, price=price)
        if discounts:
            for discount in discounts:
                item.discounts.add(discount)
            item.save()

    def handle(self, *args, **options):
        print("Populating with Fest menu..")
        schoteldag = Discount.objects.create(
            name="Schoteldag", days='2,3', relative=True, value=200)
        pizzadag25 = Discount.objects.create(
            name="Pizzadag (t/m 25)", days='0,1', relative=False, value=600)
        pizzadag2635 = Discount.objects.create(
            name="Pizzadag (26 t/m 35)", days='0,1', relative=False, value=800)

        self._add_item("Friet zonder (klein)", 160)
        self._add_item("Friet zonder (groot)", 210)
        self._add_item("Friet mayonaise (klein)", 200)
        self._add_item("Friet mayonaise (groot)", 230)
        self._add_item("Friet speciaal (klein)", 220)
        self._add_item("Friet speciaal (groot)", 270)
        self._add_item("Friet saté (klein)", 220)
        self._add_item("Friet saté (groot)", 270)
        self._add_item("Friet oorlog (klein)", 240)
        self._add_item("Friet oorlog (groot)", 290)
        self._add_item("Friet stoofvlees (klein)", 300)
        self._add_item("Friet stoofvlees (groot)", 350)
        self._add_item("Friet super (klein)", 375)
        self._add_item("Friet super (groot)", 425)
        self._add_item("Friet super saté (klein)", 375)
        self._add_item("Friet super saté (groot)", 425)
        self._add_item("Friet super oorlog (klein)", 400)
        self._add_item("Friet super oorlog (groot)", 450)
        self._add_item("Friet waterfiets (klein)", 450)
        self._add_item("Friet waterfiets (groot)", 500)
        self._add_item("Friet knoflook (klein)", 220)
        self._add_item("Friet knoflook (groot)", 270)
        self._add_item("Friet joppie (klein)", 220)
        self._add_item("Friet joppie (groot)", 270)
        self._add_item("Gezinszak friet", 500)
        self._add_item("extra ras/aardappel", 25)

        self._add_item("Frikandel", 150)
        self._add_item("Frikandel speciaal", 190)
        self._add_item("Kroket", 150)
        self._add_item("Goulash kroket", 160)
        self._add_item("Satékroket", 160)
        self._add_item("Bamischijf", 160)
        self._add_item("Nasischijf", 160)
        self._add_item("Gehaktbal", 200)
        self._add_item("Kwekkerboom", 180)
        self._add_item("Pikanto", 210)
        self._add_item("Kipcorn", 190)
        self._add_item("Mexicano", 210)
        self._add_item("Lihanboutje", 160)
        self._add_item("Bitterballen (10st)", 250)
        self._add_item("Viandel", 210)
        self._add_item("Braadworst", 210)
        self._add_item("Knakworst", 210)
        self._add_item("Sitostick", 210)
        self._add_item("Visstick", 220)
        self._add_item("Berenklauw", 220)
        self._add_item("Smulrol", 220)
        self._add_item("Shoarmarol", 220)
        self._add_item("Loempia klein", 160)
        self._add_item("Loempia groot", 275)
        self._add_item("Vlammetjes (6st)", 250)
        self._add_item("Kipnuggets (6st)", 250)
        self._add_item("Mini nais of bami (6st)", 250)
        self._add_item("Nasi vegetarisch", 190)
        self._add_item("Bami vegetarisch", 190)
        self._add_item("Cheese crack", 190)
        self._add_item("Kaassoufflé", 160)

        self._add_item("Dürüm döner", 500)
        self._add_item("Dürüm shoarma", 500)
        self._add_item("Dürüm kip döner", 500)

        self._add_item("Rundvleessalade", 200)
        self._add_item("Gemengde salade", 200)
        self._add_item("Salade de Fest", 600)
        self._add_item("Salade tonno", 500)

        self._add_item("Broodje kroket", 200)
        self._add_item("Broodje frikandel", 200)
        self._add_item("Broodje viandel", 250)
        self._add_item("Broodje kipkorn", 230)
        self._add_item("Broodje gehaktbal", 250)
        self._add_item("Broodje braadworst", 260)
        self._add_item("Broodje knakworst", 260)
        self._add_item("Broodje pikanto", 260)
        self._add_item("Broodje mexicano", 260)
        self._add_item("Broodje visstick", 270)
        self._add_item("Broodje goulashkroket", 210)
        self._add_item("Broodje satékroket", 210)
        self._add_item("Broodje ham", 200)
        self._add_item("Broodje ham en kaas", 250)

        self._add_item("Portie satéstokjes", 450)
        self._add_item("Satéschotel", 800, schoteldag)

        self._add_item("Halve haan", 500, schoteldag)
        self._add_item("Halve-haan-schotel", 900, schoteldag)

        self._add_item("Broodje hamburger speciaal", 300)
        self._add_item("Broodje hamburger Hawaï", 400)
        self._add_item("Hamburgerschotel", 850, schoteldag)
        self._add_item("Hamburgerschotel Hawaï", 900, schoteldag)

        self._add_item("Broodje kipfilet", 600)
        self._add_item("Broodje kip groot", 800)
        self._add_item("Friet kip", 800)
        self._add_item("Kipschotel", 1000, schoteldag)

        self._add_item("Broodje shoarma", 500)
        self._add_item("Broodje shoarma fantasie", 600)
        self._add_item("Broodje shoarma groot", 700)
        self._add_item("Broodje shoarma ananas", 600)
        self._add_item("Broodje shoarma kaas", 600)
        self._add_item("Friet shoarma", 700)
        self._add_item("Friet shoarma kaas", 800)
        self._add_item("Shoarmaschotel", 900, schoteldag)
        self._add_item("Shoarmaschotel fantasie", 1000, schoteldag)
        self._add_item("Shoarmaschotel ananas", 1000, schoteldag)

        self._add_item("Broodje döner", 500)
        self._add_item("Broodje döner fantasie", 600)
        self._add_item("Broodje döner groot", 700)
        self._add_item("Friet döner", 700)
        self._add_item("Dönerschotel", 900, schoteldag)
        self._add_item("Dönerschotel fantasie", 1000, schoteldag)

        self._add_item("Broodje kipdöner", 500)
        self._add_item("Broodje kipdöner fantasie", 600)
        self._add_item("Broodje kipdöner ananas", 600)
        self._add_item("Friet kipdöner", 700)
        self._add_item("Kipdönerschotel", 900, schoteldag)
        self._add_item("Kipdönerschotel fantasie", 1000, schoteldag)
        self._add_item("Kipdönerschotel ananas", 1000, schoteldag)

        self._add_item("Lahmacun met groente", 300)
        self._add_item("Lahmacun met döner", 500)
        self._add_item("Lahmacun met shoarma", 500)
        self._add_item("Lahmacun met kipdöner", 500)

        self._add_item("Kapsalon vegetarisch (klein)", 650)
        self._add_item("Kapsalon vegetarisch (groot)", 850)
        self._add_item("Kapsalon döner (klein)", 650)
        self._add_item("Kapsalon döner (groot)", 850)
        self._add_item("Kapsalon shoarma (klein)", 650)
        self._add_item("Kapsalon shoarma (groot)", 850)
        self._add_item("Kapsalon kipdöner (klein)", 650)
        self._add_item("Kapsalon kipdöner (groot)", 850)
        self._add_item("Kapsalon kipfilet (klein)", 650)
        self._add_item("Kapsalon kipfilet (groot)", 850)

        self._add_item("Spareribsschotel", 1200, schoteldag)

        self._add_item("Kaassouffléschotel", 700, schoteldag)
        self._add_item("Kroketschotel", 750, schoteldag)
        self._add_item("Frikandelschotel", 750, schoteldag)
        self._add_item("Pikantoschotel", 850, schoteldag)
        self._add_item("Mexicanoschotel", 850, schoteldag)
        self._add_item("Kipcornschotel", 850, schoteldag)

        self._add_item("Shoarma-/dönerschotel", 1100, schoteldag)
        self._add_item("Shoarma-/kipdönerschotel", 1100, schoteldag)
        self._add_item("Shoarma-/kipfiletschotel", 1100, schoteldag)

        self._add_item("Schnitzelschotel", 800, schoteldag)
        self._add_item("Schnitzel champignons", 1000, schoteldag)
        self._add_item("Schnitzel zigeunersaus", 900, schoteldag)

        self._add_item("Margherita", 750, pizzadag25)
        self._add_item("Bianca", 750, pizzadag25)
        self._add_item("Napolitana", 750, pizzadag25)
        self._add_item("Funghi", 750, pizzadag25)
        self._add_item("Borromea", 750, pizzadag25)
        self._add_item("Vesuvio", 750, pizzadag25)
        self._add_item("Peperoni", 750, pizzadag25)
        self._add_item("Salami", 750, pizzadag25)
        self._add_item("Romagna", 750, pizzadag25)
        self._add_item("Siciliana", 750, pizzadag25)
        self._add_item("Quatro stagioni", 750, pizzadag25)
        self._add_item("Pollo", 750, pizzadag25)
        self._add_item("Capricciosa", 750, pizzadag25)
        self._add_item("Tonno", 750, pizzadag25)
        self._add_item("Vegetaria", 750, pizzadag25)
        self._add_item("Spinazi", 750, pizzadag25)
        self._add_item("Pizza döner speciaal", 750, pizzadag25)
        self._add_item("Pizza shoarma speciaal", 750, pizzadag25)
        self._add_item("Pizza shoarma", 750, pizzadag25)
        self._add_item("Pizza döner kebab", 750, pizzadag25)
        self._add_item("Estete", 750, pizzadag25)
        self._add_item("Gorgonzola al fromaggio", 750, pizzadag25)
        self._add_item("Hawaï", 750, pizzadag25)
        self._add_item("Campagnola", 750, pizzadag25)
        self._add_item("Roma", 750, pizzadag25)
        self._add_item("Carbonara", 750, pizzadag25)

        self._add_item("Funghi e pesce", 750, pizzadag2635)
        self._add_item("Mafiosa", 750, pizzadag2635)
        self._add_item("Santa Maria", 750, pizzadag2635)
        self._add_item("Paescana speciale", 750, pizzadag2635)
        self._add_item("Marinara", 750, pizzadag2635)
        self._add_item("Pizza De Fest speciaal", 750, pizzadag2635)
        self._add_item("Calzone vegatarisch", 750, pizzadag2635)
        self._add_item("Calzone shoarma", 750, pizzadag2635)
        self._add_item("Calzone kip", 750, pizzadag2635)
        self._add_item("Calzone fantasie", 750, pizzadag2635)
        self._add_item("Calzone de Fest", 750, pizzadag2635)
        self._add_item("-extra vlees", 200)
        self._add_item("-extra groente of fruit", 50)
        self._add_item("-extra ham of salami", 100)

        self._add_item("Knoflooksaus", 75)
        self._add_item("Mayonaise", 75)
        self._add_item("Sambalsaus", 75)
        self._add_item("Tomatensaus", 75)
        self._add_item("Cocktailsaus", 75)
        self._add_item("Joppiesaus", 100)
        self._add_item("Currysaus", 100)
        self._add_item("Satésaus (klein)", 125)
        self._add_item("Satésaus (groot)", 250)
