# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations


def categorise_fest(apps, schema_editor):
    Category = apps.get_model("orders", "Category")
    Item = apps.get_model("orders", "Item")
    # .pk should not be required, but this is a bug in Django 1.8
    # this is influenced by the same bug as trac:24573 and fixed by its patch
    friet = Category.objects.create(name="Friet of rasfriet")
    friet.items.add(Item.objects.get(name="Friet zonder (klein)").pk)
    friet.items.add(Item.objects.get(name="Friet zonder (groot)").pk)
    friet.items.add(Item.objects.get(name="Friet mayonaise (klein)").pk)
    friet.items.add(Item.objects.get(name="Friet mayonaise (groot)").pk)
    friet.items.add(Item.objects.get(name="Friet speciaal (klein)").pk)
    friet.items.add(Item.objects.get(name="Friet speciaal (groot)").pk)
    friet.items.add(Item.objects.get(name="Friet saté (klein)").pk)
    friet.items.add(Item.objects.get(name="Friet saté (groot)").pk)
    friet.items.add(Item.objects.get(name="Friet oorlog (klein)").pk)
    friet.items.add(Item.objects.get(name="Friet oorlog (groot)").pk)
    friet.items.add(Item.objects.get(name="Friet stoofvlees (klein)").pk)
    friet.items.add(Item.objects.get(name="Friet stoofvlees (groot)").pk)
    friet.items.add(Item.objects.get(name="Friet super (klein)").pk)
    friet.items.add(Item.objects.get(name="Friet super (groot)").pk)
    friet.items.add(Item.objects.get(name="Friet super saté (klein)").pk)
    friet.items.add(Item.objects.get(name="Friet super saté (groot)").pk)
    friet.items.add(Item.objects.get(name="Friet super oorlog (klein)").pk)
    friet.items.add(Item.objects.get(name="Friet super oorlog (groot)").pk)
    friet.items.add(Item.objects.get(name="Friet waterfiets (klein)").pk)
    friet.items.add(Item.objects.get(name="Friet waterfiets (groot)").pk)
    friet.items.add(Item.objects.get(name="Friet knoflook (klein)").pk)
    friet.items.add(Item.objects.get(name="Friet knoflook (groot)").pk)
    friet.items.add(Item.objects.get(name="Friet joppie (klein)").pk)
    friet.items.add(Item.objects.get(name="Friet joppie (groot)").pk)
    friet.items.add(Item.objects.get(name="Gezinszak friet").pk)
    friet.items.add(Item.objects.get(name="extra ras/aardappel").pk)

    snacks = Category.objects.create(name="Snacks")
    snacks.items.add(Item.objects.get(name="Frikandel").pk)
    snacks.items.add(Item.objects.get(name="Frikandel speciaal").pk)
    snacks.items.add(Item.objects.get(name="Kroket").pk)
    snacks.items.add(Item.objects.get(name="Goulash kroket").pk)
    snacks.items.add(Item.objects.get(name="Satékroket").pk)
    snacks.items.add(Item.objects.get(name="Bamischijf").pk)
    snacks.items.add(Item.objects.get(name="Nasischijf").pk)
    snacks.items.add(Item.objects.get(name="Gehaktbal").pk)
    snacks.items.add(Item.objects.get(name="Kwekkerboom").pk)
    snacks.items.add(Item.objects.get(name="Pikanto").pk)
    snacks.items.add(Item.objects.get(name="Kipcorn").pk)
    snacks.items.add(Item.objects.get(name="Mexicano").pk)
    snacks.items.add(Item.objects.get(name="Lihanboutje").pk)
    snacks.items.add(Item.objects.get(name="Bitterballen (10st)").pk)
    snacks.items.add(Item.objects.get(name="Viandel").pk)
    snacks.items.add(Item.objects.get(name="Braadworst").pk)
    snacks.items.add(Item.objects.get(name="Knakworst").pk)
    snacks.items.add(Item.objects.get(name="Sitostick").pk)
    snacks.items.add(Item.objects.get(name="Visstick").pk)
    snacks.items.add(Item.objects.get(name="Berenklauw").pk)
    snacks.items.add(Item.objects.get(name="Smulrol").pk)
    snacks.items.add(Item.objects.get(name="Shoarmarol").pk)
    snacks.items.add(Item.objects.get(name="Loempia klein").pk)
    snacks.items.add(Item.objects.get(name="Loempia groot").pk)
    snacks.items.add(Item.objects.get(name="Vlammetjes (6st)").pk)
    snacks.items.add(Item.objects.get(name="Kipnuggets (6st)").pk)
    snacks.items.add(Item.objects.get(name="Mini nasi (6st)").pk)
    snacks.items.add(Item.objects.get(name="Mini bami (6st)").pk)
    snacks.items.add(Item.objects.get(name="Nasi vegetarisch").pk)
    snacks.items.add(Item.objects.get(name="Bami vegetarisch").pk)
    snacks.items.add(Item.objects.get(name="Cheese crack").pk)
    snacks.items.add(Item.objects.get(name="Kaassoufflé").pk)

    durum = Category.objects.create(name="Dürüm")
    durum.items.add(Item.objects.get(name="Dürüm döner").pk)
    durum.items.add(Item.objects.get(name="Dürüm shoarma").pk)
    durum.items.add(Item.objects.get(name="Dürüm kip döner").pk)

    salades = Category.objects.create(name="Salades")
    salades.items.add(Item.objects.get(name="Rundvleessalade").pk)
    salades.items.add(Item.objects.get(name="Gemengde salade").pk)
    salades.items.add(Item.objects.get(name="Salade de Fest").pk)
    salades.items.add(Item.objects.get(name="Salade tonno").pk)

    broodjes = Category.objects.create(name="Broodjes")
    broodjes.items.add(Item.objects.get(name="Broodje kroket").pk)
    broodjes.items.add(Item.objects.get(name="Broodje frikandel").pk)
    broodjes.items.add(Item.objects.get(name="Broodje viandel").pk)
    broodjes.items.add(Item.objects.get(name="Broodje kipkorn").pk)
    broodjes.items.add(Item.objects.get(name="Broodje gehaktbal").pk)
    broodjes.items.add(Item.objects.get(name="Broodje braadworst").pk)
    broodjes.items.add(Item.objects.get(name="Broodje knakworst").pk)
    broodjes.items.add(Item.objects.get(name="Broodje pikanto").pk)
    broodjes.items.add(Item.objects.get(name="Broodje mexicano").pk)
    broodjes.items.add(Item.objects.get(name="Broodje visstick").pk)
    broodjes.items.add(Item.objects.get(name="Broodje goulashkroket").pk)
    broodjes.items.add(Item.objects.get(name="Broodje satékroket").pk)
    broodjes.items.add(Item.objects.get(name="Broodje ham").pk)
    broodjes.items.add(Item.objects.get(name="Broodje ham en kaas").pk)

    satestokjes = Category.objects.create(name="Satéstokjes")
    satestokjes.items.add(Item.objects.get(name="Portie satéstokjes").pk)
    satestokjes.items.add(Item.objects.get(name="Satéschotel").pk)

    halvehaan = Category.objects.create(name="Halve haan")
    halvehaan.items.add(Item.objects.get(name="Halve haan").pk)
    halvehaan.items.add(Item.objects.get(name="Halve-haan-schotel").pk)

    hamburgers = Category.objects.create(name="Hamburgers")
    hamburgers.items.add(Item.objects.get(name="Broodje hamburger speciaal").pk)
    hamburgers.items.add(Item.objects.get(name="Broodje hamburger Hawaï").pk)
    hamburgers.items.add(Item.objects.get(name="Hamburgerschotel").pk)
    hamburgers.items.add(Item.objects.get(name="Hamburgerschotel Hawaï").pk)

    kipfilet = Category.objects.create(name="Kipfilet")
    kipfilet.items.add(Item.objects.get(name="Broodje kipfilet").pk)
    kipfilet.items.add(Item.objects.get(name="Broodje kip groot").pk)
    kipfilet.items.add(Item.objects.get(name="Friet kip").pk)
    kipfilet.items.add(Item.objects.get(name="Kipschotel").pk)

    shoarma = Category.objects.create(name="Shoarma")
    shoarma.items.add(Item.objects.get(name="Broodje shoarma").pk)
    shoarma.items.add(Item.objects.get(name="Broodje shoarma fantasie").pk)
    shoarma.items.add(Item.objects.get(name="Broodje shoarma groot").pk)
    shoarma.items.add(Item.objects.get(name="Broodje shoarma ananas").pk)
    shoarma.items.add(Item.objects.get(name="Broodje shoarma kaas").pk)
    shoarma.items.add(Item.objects.get(name="Friet shoarma").pk)
    shoarma.items.add(Item.objects.get(name="Friet shoarma kaas").pk)
    shoarma.items.add(Item.objects.get(name="Shoarmaschotel").pk)
    shoarma.items.add(Item.objects.get(name="Shoarmaschotel fantasie").pk)
    shoarma.items.add(Item.objects.get(name="Shoarmaschotel ananas").pk)

    doner = Category.objects.create(name="Döner")
    doner.items.add(Item.objects.get(name="Broodje döner").pk)
    doner.items.add(Item.objects.get(name="Broodje döner fantasie").pk)
    doner.items.add(Item.objects.get(name="Broodje döner groot").pk)
    doner.items.add(Item.objects.get(name="Friet döner").pk)
    doner.items.add(Item.objects.get(name="Dönerschotel").pk)
    doner.items.add(Item.objects.get(name="Dönerschotel fantasie").pk)

    kipdoner = Category.objects.create(name="Kipdöner")
    kipdoner.items.add(Item.objects.get(name="Broodje kipdöner").pk)
    kipdoner.items.add(Item.objects.get(name="Broodje kipdöner fantasie").pk)
    kipdoner.items.add(Item.objects.get(name="Broodje kipdöner ananas").pk)
    kipdoner.items.add(Item.objects.get(name="Friet kipdöner").pk)
    kipdoner.items.add(Item.objects.get(name="Kipdönerschotel").pk)
    kipdoner.items.add(Item.objects.get(name="Kipdönerschotel fantasie").pk)
    kipdoner.items.add(Item.objects.get(name="Kipdönerschotel ananas").pk)

    lahmacun = Category.objects.create(name="Turkse pizza lahmacun")
    lahmacun.items.add(Item.objects.get(name="Lahmacun met groente").pk)
    lahmacun.items.add(Item.objects.get(name="Lahmacun met döner").pk)
    lahmacun.items.add(Item.objects.get(name="Lahmacun met shoarma").pk)
    lahmacun.items.add(Item.objects.get(name="Lahmacun met kipdöner").pk)

    kapsalons = Category.objects.create(name="Kapsalons")
    kapsalons.items.add(Item.objects.get(name="Kapsalon vegetarisch (klein)").pk)
    kapsalons.items.add(Item.objects.get(name="Kapsalon vegetarisch (groot)").pk)
    kapsalons.items.add(Item.objects.get(name="Kapsalon döner (klein)").pk)
    kapsalons.items.add(Item.objects.get(name="Kapsalon döner (groot)").pk)
    kapsalons.items.add(Item.objects.get(name="Kapsalon shoarma (klein)").pk)
    kapsalons.items.add(Item.objects.get(name="Kapsalon shoarma (groot)").pk)
    kapsalons.items.add(Item.objects.get(name="Kapsalon kipdöner (klein)").pk)
    kapsalons.items.add(Item.objects.get(name="Kapsalon kipdöner (groot)").pk)
    kapsalons.items.add(Item.objects.get(name="Kapsalon kipfilet (klein)").pk)
    kapsalons.items.add(Item.objects.get(name="Kapsalon kipfilet (groot)").pk)

    spareribs = Category.objects.create(name="Spareribs")
    spareribs.items.add(Item.objects.get(name="Spareribsschotel").pk)

    snackschotels = Category.objects.create(name="Snackschotels")
    snackschotels.items.add(Item.objects.get(name="Kaassouffléschotel").pk)
    snackschotels.items.add(Item.objects.get(name="Kroketschotel").pk)
    snackschotels.items.add(Item.objects.get(name="Frikandelschotel").pk)
    snackschotels.items.add(Item.objects.get(name="Pikantoschotel").pk)
    snackschotels.items.add(Item.objects.get(name="Mexicanoschotel").pk)
    snackschotels.items.add(Item.objects.get(name="Kipcornschotel").pk)

    mixschotels = Category.objects.create(name="Mixschotels")
    mixschotels.items.add(Item.objects.get(name="Shoarma-/dönerschotel").pk)
    mixschotels.items.add(Item.objects.get(name="Shoarma-/kipdönerschotel").pk)
    mixschotels.items.add(Item.objects.get(name="Shoarma-/kipfiletschotel").pk)

    schnitzelschotel = Category.objects.create(name="Schnitzelschotels")
    schnitzelschotel.items.add(Item.objects.get(name="Schnitzelschotel").pk)
    schnitzelschotel.items.add(Item.objects.get(name="Schnitzel champignons").pk)
    schnitzelschotel.items.add(Item.objects.get(name="Schnitzel zigeunersaus").pk)

    pizzas = Category.objects.create(name="Pizza's")
    pizzas.items.add(Item.objects.get(name="Margherita (nr. 1)").pk)
    pizzas.items.add(Item.objects.get(name="Bianca (nr. 2)").pk)
    pizzas.items.add(Item.objects.get(name="Napolitana (nr. 3)").pk)
    pizzas.items.add(Item.objects.get(name="Funghi (nr. 4)").pk)
    pizzas.items.add(Item.objects.get(name="Borromea (nr. 5)").pk)
    pizzas.items.add(Item.objects.get(name="Vesuvio (nr. 6)").pk)
    pizzas.items.add(Item.objects.get(name="Peperoni (nr. 7)").pk)
    pizzas.items.add(Item.objects.get(name="Salami (nr. 8)").pk)
    pizzas.items.add(Item.objects.get(name="Romagna (nr. 9)").pk)
    pizzas.items.add(Item.objects.get(name="Siciliana (nr. 10)").pk)
    pizzas.items.add(Item.objects.get(name="Quatro stagioni (nr. 11)").pk)
    pizzas.items.add(Item.objects.get(name="Pollo (nr. 12)").pk)
    pizzas.items.add(Item.objects.get(name="Capricciosa (nr. 13)").pk)
    pizzas.items.add(Item.objects.get(name="Tonno (nr. 14)").pk)
    pizzas.items.add(Item.objects.get(name="Vegetaria (nr. 15)").pk)
    pizzas.items.add(Item.objects.get(name="Spinazie (nr. 16)").pk)
    pizzas.items.add(Item.objects.get(name="Pizza döner speciaal (nr. 17)").pk)
    pizzas.items.add(Item.objects.get(name="Pizza shoarma speciaal (nr. 17)").pk)
    pizzas.items.add(Item.objects.get(name="Pizza shoarma (nr. 18)").pk)
    pizzas.items.add(Item.objects.get(name="Pizza döner kebab (nr. 19)").pk)
    pizzas.items.add(Item.objects.get(name="Estete (nr. 20)").pk)
    pizzas.items.add(Item.objects.get(name="Gorgonzola al fromaggio (nr. 21)").pk)
    pizzas.items.add(Item.objects.get(name="Hawaï (nr. 22)").pk)
    pizzas.items.add(Item.objects.get(name="Campagnola (nr. 23)").pk)
    pizzas.items.add(Item.objects.get(name="Roma (nr. 24)").pk)
    pizzas.items.add(Item.objects.get(name="Carbonara (nr. 25)").pk)

    pizzas.items.add(Item.objects.get(name="Funghi e pesce (nr. 26)").pk)
    pizzas.items.add(Item.objects.get(name="Mafiosa (nr. 27)").pk)
    pizzas.items.add(Item.objects.get(name="Santa Maria (nr. 28)").pk)
    pizzas.items.add(Item.objects.get(name="Paescana speciale (nr. 29)").pk)
    pizzas.items.add(Item.objects.get(name="Marinara (nr. 30)").pk)
    pizzas.items.add(Item.objects.get(name="Pizza De Fest speciaal (nr. 31)").pk)
    pizzas.items.add(Item.objects.get(name="Calzone vegatarisch (nr. 32)").pk)
    pizzas.items.add(Item.objects.get(name="Calzone shoarma (nr. 33)").pk)
    pizzas.items.add(Item.objects.get(name="Calzone kip (nr. 34)").pk)
    pizzas.items.add(Item.objects.get(name="Calzone fantasie (nr. 35)").pk)
    pizzas.items.add(Item.objects.get(name="Calzone de Fest (nr. 36)").pk)
    pizzas.items.add(Item.objects.get(name="-extra vlees").pk)
    pizzas.items.add(Item.objects.get(name="-extra groente of fruit").pk)
    pizzas.items.add(Item.objects.get(name="-extra ham of salami").pk)

    sauzen = Category.objects.create(name="Sauzen")
    sauzen.items.add(Item.objects.get(name="Knoflooksaus").pk)
    sauzen.items.add(Item.objects.get(name="Mayonaise").pk)
    sauzen.items.add(Item.objects.get(name="Sambalsaus").pk)
    sauzen.items.add(Item.objects.get(name="Tomatensaus").pk)
    sauzen.items.add(Item.objects.get(name="Cocktailsaus").pk)
    sauzen.items.add(Item.objects.get(name="Joppiesaus").pk)
    sauzen.items.add(Item.objects.get(name="Currysaus").pk)
    sauzen.items.add(Item.objects.get(name="Satésaus (klein)").pk)
    sauzen.items.add(Item.objects.get(name="Satésaus (groot)").pk)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_populatefest'),
    ]

    operations = [
        migrations.RunPython(categorise_fest)
    ]
