# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations


def categorise_fest(apps, schema_editor):
    Category = apps.get_model("orders", "Category")
    Item = apps.get_model("orders", "Item")

    friet = Category.objects.create(name="Friet of rasfriet")
    friet.items.add(Item.objects.get(name="Friet zonder (klein)"))
    friet.items.add(Item.objects.get(name="Friet zonder (groot)"))
    friet.items.add(Item.objects.get(name="Friet mayonaise (klein)"))
    friet.items.add(Item.objects.get(name="Friet mayonaise (groot)"))
    friet.items.add(Item.objects.get(name="Friet speciaal (klein)"))
    friet.items.add(Item.objects.get(name="Friet speciaal (groot)"))
    friet.items.add(Item.objects.get(name="Friet saté (klein)"))
    friet.items.add(Item.objects.get(name="Friet saté (groot)"))
    friet.items.add(Item.objects.get(name="Friet oorlog (klein)"))
    friet.items.add(Item.objects.get(name="Friet oorlog (groot)"))
    friet.items.add(Item.objects.get(name="Friet stoofvlees (klein)"))
    friet.items.add(Item.objects.get(name="Friet stoofvlees (groot)"))
    friet.items.add(Item.objects.get(name="Friet super (klein)"))
    friet.items.add(Item.objects.get(name="Friet super (groot)"))
    friet.items.add(Item.objects.get(name="Friet super saté (klein)"))
    friet.items.add(Item.objects.get(name="Friet super saté (groot)"))
    friet.items.add(Item.objects.get(name="Friet super oorlog (klein)"))
    friet.items.add(Item.objects.get(name="Friet super oorlog (groot)"))
    friet.items.add(Item.objects.get(name="Friet waterfiets (klein)"))
    friet.items.add(Item.objects.get(name="Friet waterfiets (groot)"))
    friet.items.add(Item.objects.get(name="Friet knoflook (klein)"))
    friet.items.add(Item.objects.get(name="Friet knoflook (groot)"))
    friet.items.add(Item.objects.get(name="Friet joppie (klein)"))
    friet.items.add(Item.objects.get(name="Friet joppie (groot)"))
    friet.items.add(Item.objects.get(name="Gezinszak friet"))
    friet.items.add(Item.objects.get(name="extra ras/aardappel"))

    snacks = Category.objects.create(name="Snacks")
    snacks.items.add(Item.objects.get(name="Frikandel"))
    snacks.items.add(Item.objects.get(name="Frikandel speciaal"))
    snacks.items.add(Item.objects.get(name="Kroket"))
    snacks.items.add(Item.objects.get(name="Goulash kroket"))
    snacks.items.add(Item.objects.get(name="Satékroket"))
    snacks.items.add(Item.objects.get(name="Bamischijf"))
    snacks.items.add(Item.objects.get(name="Nasischijf"))
    snacks.items.add(Item.objects.get(name="Gehaktbal"))
    snacks.items.add(Item.objects.get(name="Kwekkerboom"))
    snacks.items.add(Item.objects.get(name="Pikanto"))
    snacks.items.add(Item.objects.get(name="Kipcorn"))
    snacks.items.add(Item.objects.get(name="Mexicano"))
    snacks.items.add(Item.objects.get(name="Lihanboutje"))
    snacks.items.add(Item.objects.get(name="Bitterballen (10st)"))
    snacks.items.add(Item.objects.get(name="Viandel"))
    snacks.items.add(Item.objects.get(name="Braadworst"))
    snacks.items.add(Item.objects.get(name="Knakworst"))
    snacks.items.add(Item.objects.get(name="Sitostick"))
    snacks.items.add(Item.objects.get(name="Visstick"))
    snacks.items.add(Item.objects.get(name="Berenklauw"))
    snacks.items.add(Item.objects.get(name="Smulrol"))
    snacks.items.add(Item.objects.get(name="Shoarmarol"))
    snacks.items.add(Item.objects.get(name="Loempia klein"))
    snacks.items.add(Item.objects.get(name="Loempia groot"))
    snacks.items.add(Item.objects.get(name="Vlammetjes (6st)"))
    snacks.items.add(Item.objects.get(name="Kipnuggets (6st)"))
    snacks.items.add(Item.objects.get(name="Mini nasi (6st)"))
    snacks.items.add(Item.objects.get(name="Mini bami (6st)"))
    snacks.items.add(Item.objects.get(name="Nasi vegetarisch"))
    snacks.items.add(Item.objects.get(name="Bami vegetarisch"))
    snacks.items.add(Item.objects.get(name="Cheese crack"))
    snacks.items.add(Item.objects.get(name="Kaassoufflé"))

    durum = Category.objects.create(name="Dürüm")
    durum.items.add(Item.objects.get(name="Dürüm döner"))
    durum.items.add(Item.objects.get(name="Dürüm shoarma"))
    durum.items.add(Item.objects.get(name="Dürüm kip döner"))

    salades = Category.objects.create(name="Salades")
    salades.items.add(Item.objects.get(name="Rundvleessalade"))
    salades.items.add(Item.objects.get(name="Gemengde salade"))
    salades.items.add(Item.objects.get(name="Salade de Fest"))
    salades.items.add(Item.objects.get(name="Salade tonno"))

    broodjes = Category.objects.create(name="Broodjes")
    broodjes.items.add(Item.objects.get(name="Broodje kroket"))
    broodjes.items.add(Item.objects.get(name="Broodje frikandel"))
    broodjes.items.add(Item.objects.get(name="Broodje viandel"))
    broodjes.items.add(Item.objects.get(name="Broodje kipkorn"))
    broodjes.items.add(Item.objects.get(name="Broodje gehaktbal"))
    broodjes.items.add(Item.objects.get(name="Broodje braadworst"))
    broodjes.items.add(Item.objects.get(name="Broodje knakworst"))
    broodjes.items.add(Item.objects.get(name="Broodje pikanto"))
    broodjes.items.add(Item.objects.get(name="Broodje mexicano"))
    broodjes.items.add(Item.objects.get(name="Broodje visstick"))
    broodjes.items.add(Item.objects.get(name="Broodje goulashkroket"))
    broodjes.items.add(Item.objects.get(name="Broodje satékroket"))
    broodjes.items.add(Item.objects.get(name="Broodje ham"))
    broodjes.items.add(Item.objects.get(name="Broodje ham en kaas"))

    satestokjes = Category.objects.create(name="Satéstokjes")
    satestokjes.items.add(Item.objects.get(name="Portie satéstokjes"))
    satestokjes.items.add(Item.objects.get(name="Satéschotel"))

    halvehaan = Category.objects.create(name="Halve haan")
    halvehaan.items.add(Item.objects.get(name="Halve haan"))
    halvehaan.items.add(Item.objects.get(name="Halve-haan-schotel"))

    hamburgers = Category.objects.create(name="Hamburgers")
    hamburgers.items.add(Item.objects.get(name="Broodje hamburger speciaal"))
    hamburgers.items.add(Item.objects.get(name="Broodje hamburger Hawaï"))
    hamburgers.items.add(Item.objects.get(name="Hamburgerschotel"))
    hamburgers.items.add(Item.objects.get(name="Hamburgerschotel Hawaï"))

    kipfilet = Category.objects.create(name="Kipfilet")
    kipfilet.items.add(Item.objects.get(name="Broodje kipfilet"))
    kipfilet.items.add(Item.objects.get(name="Broodje kip groot"))
    kipfilet.items.add(Item.objects.get(name="Friet kip"))
    kipfilet.items.add(Item.objects.get(name="Kipschotel"))

    shoarma = Category.objects.create(name="Shoarma")
    shoarma.items.add(Item.objects.get(name="Broodje shoarma"))
    shoarma.items.add(Item.objects.get(name="Broodje shoarma fantasie"))
    shoarma.items.add(Item.objects.get(name="Broodje shoarma groot"))
    shoarma.items.add(Item.objects.get(name="Broodje shoarma ananas"))
    shoarma.items.add(Item.objects.get(name="Broodje shoarma kaas"))
    shoarma.items.add(Item.objects.get(name="Friet shoarma"))
    shoarma.items.add(Item.objects.get(name="Friet shoarma kaas"))
    shoarma.items.add(Item.objects.get(name="Shoarmaschotel"))
    shoarma.items.add(Item.objects.get(name="Shoarmaschotel fantasie"))
    shoarma.items.add(Item.objects.get(name="Shoarmaschotel ananas"))

    doner = Category.objects.create(name="Döner")
    doner.items.add(Item.objects.get(name="Broodje döner"))
    doner.items.add(Item.objects.get(name="Broodje döner fantasie"))
    doner.items.add(Item.objects.get(name="Broodje döner groot"))
    doner.items.add(Item.objects.get(name="Friet döner"))
    doner.items.add(Item.objects.get(name="Dönerschotel"))
    doner.items.add(Item.objects.get(name="Dönerschotel fantasie"))

    kipdoner = Category.objects.create(name="Kipdöner")
    kipdoner.items.add(Item.objects.get(name="Broodje kipdöner"))
    kipdoner.items.add(Item.objects.get(name="Broodje kipdöner fantasie"))
    kipdoner.items.add(Item.objects.get(name="Broodje kipdöner ananas"))
    kipdoner.items.add(Item.objects.get(name="Friet kipdöner"))
    kipdoner.items.add(Item.objects.get(name="Kipdönerschotel"))
    kipdoner.items.add(Item.objects.get(name="Kipdönerschotel fantasie"))
    kipdoner.items.add(Item.objects.get(name="Kipdönerschotel ananas"))

    lahmacun = Category.objects.create(name="Turkse pizza lahmacun")
    lahmacun.items.add(Item.objects.get(name="Lahmacun met groente"))
    lahmacun.items.add(Item.objects.get(name="Lahmacun met döner"))
    lahmacun.items.add(Item.objects.get(name="Lahmacun met shoarma"))
    lahmacun.items.add(Item.objects.get(name="Lahmacun met kipdöner"))

    kapsalons = Category.objects.create(name="Kapsalons")
    kapsalons.items.add(Item.objects.get(name="Kapsalon vegetarisch (klein)"))
    kapsalons.items.add(Item.objects.get(name="Kapsalon vegetarisch (groot)"))
    kapsalons.items.add(Item.objects.get(name="Kapsalon döner (klein)"))
    kapsalons.items.add(Item.objects.get(name="Kapsalon döner (groot)"))
    kapsalons.items.add(Item.objects.get(name="Kapsalon shoarma (klein)"))
    kapsalons.items.add(Item.objects.get(name="Kapsalon shoarma (groot)"))
    kapsalons.items.add(Item.objects.get(name="Kapsalon kipdöner (klein)"))
    kapsalons.items.add(Item.objects.get(name="Kapsalon kipdöner (groot)"))
    kapsalons.items.add(Item.objects.get(name="Kapsalon kipfilet (klein)"))
    kapsalons.items.add(Item.objects.get(name="Kapsalon kipfilet (groot)"))

    spareribs = Category.objects.create(name="Spareribs")
    spareribs.items.add(Item.objects.get(name="Spareribsschotel"))

    snackschotels = Category.objects.create(name="Snackschotels")
    snackschotels.items.add(Item.objects.get(name="Kaassouffléschotel"))
    snackschotels.items.add(Item.objects.get(name="Kroketschotel"))
    snackschotels.items.add(Item.objects.get(name="Frikandelschotel"))
    snackschotels.items.add(Item.objects.get(name="Pikantoschotel"))
    snackschotels.items.add(Item.objects.get(name="Mexicanoschotel"))
    snackschotels.items.add(Item.objects.get(name="Kipcornschotel"))

    mixschotels = Category.objects.create(name="Mixschotels")
    mixschotels.items.add(Item.objects.get(name="Shoarma-/dönerschotel"))
    mixschotels.items.add(Item.objects.get(name="Shoarma-/kipdönerschotel"))
    mixschotels.items.add(Item.objects.get(name="Shoarma-/kipfiletschotel"))

    schnitzelschotel = Category.objects.create(name="Schnitzelschotels")
    schnitzelschotel.items.add(Item.objects.get(name="Schnitzelschotel"))
    schnitzelschotel.items.add(Item.objects.get(name="Schnitzel champignons"))
    schnitzelschotel.items.add(Item.objects.get(name="Schnitzel zigeunersaus"))

    pizzas = Category.objects.create(name="Pizza's")
    pizzas.items.add(Item.objects.get(name="Margherita (nr. 1)"))
    pizzas.items.add(Item.objects.get(name="Bianca (nr. 2)"))
    pizzas.items.add(Item.objects.get(name="Napolitana (nr. 3)"))
    pizzas.items.add(Item.objects.get(name="Funghi (nr. 4)"))
    pizzas.items.add(Item.objects.get(name="Borromea (nr. 5)"))
    pizzas.items.add(Item.objects.get(name="Vesuvio (nr. 6)"))
    pizzas.items.add(Item.objects.get(name="Peperoni (nr. 7)"))
    pizzas.items.add(Item.objects.get(name="Salami (nr. 8)"))
    pizzas.items.add(Item.objects.get(name="Romagna (nr. 9)"))
    pizzas.items.add(Item.objects.get(name="Siciliana (nr. 10)"))
    pizzas.items.add(Item.objects.get(name="Quatro stagioni (nr. 11)"))
    pizzas.items.add(Item.objects.get(name="Pollo (nr. 12)"))
    pizzas.items.add(Item.objects.get(name="Capricciosa (nr. 13)"))
    pizzas.items.add(Item.objects.get(name="Tonno (nr. 14)"))
    pizzas.items.add(Item.objects.get(name="Vegetaria (nr. 15)"))
    pizzas.items.add(Item.objects.get(name="Spinazie (nr. 16)"))
    pizzas.items.add(Item.objects.get(name="Pizza döner speciaal (nr. 17)"))
    pizzas.items.add(Item.objects.get(name="Pizza shoarma speciaal (nr. 17)"))
    pizzas.items.add(Item.objects.get(name="Pizza shoarma (nr. 18)"))
    pizzas.items.add(Item.objects.get(name="Pizza döner kebab (nr. 19)"))
    pizzas.items.add(Item.objects.get(name="Estete (nr. 20)"))
    pizzas.items.add(Item.objects.get(name="Gorgonzola al fromaggio (nr. 21)"))
    pizzas.items.add(Item.objects.get(name="Hawaï (nr. 22)"))
    pizzas.items.add(Item.objects.get(name="Campagnola (nr. 23)"))
    pizzas.items.add(Item.objects.get(name="Roma (nr. 24)"))
    pizzas.items.add(Item.objects.get(name="Carbonara (nr. 25)"))

    pizzas.items.add(Item.objects.get(name="Funghi e pesce (nr. 26)"))
    pizzas.items.add(Item.objects.get(name="Mafiosa (nr. 27)"))
    pizzas.items.add(Item.objects.get(name="Santa Maria (nr. 28)"))
    pizzas.items.add(Item.objects.get(name="Paescana speciale (nr. 29)"))
    pizzas.items.add(Item.objects.get(name="Marinara (nr. 30)"))
    pizzas.items.add(Item.objects.get(name="Pizza De Fest speciaal (nr. 31)"))
    pizzas.items.add(Item.objects.get(name="Calzone vegatarisch (nr. 32)"))
    pizzas.items.add(Item.objects.get(name="Calzone shoarma (nr. 33)"))
    pizzas.items.add(Item.objects.get(name="Calzone kip (nr. 34)"))
    pizzas.items.add(Item.objects.get(name="Calzone fantasie (nr. 35)"))
    pizzas.items.add(Item.objects.get(name="Calzone de Fest (nr. 36)"))
    pizzas.items.add(Item.objects.get(name="-extra vlees"))
    pizzas.items.add(Item.objects.get(name="-extra groente of fruit"))
    pizzas.items.add(Item.objects.get(name="-extra ham of salami"))

    sauzen = Category.objects.create(name="Sauzen")
    sauzen.items.add(Item.objects.get(name="Knoflooksaus"))
    sauzen.items.add(Item.objects.get(name="Mayonaise"))
    sauzen.items.add(Item.objects.get(name="Sambalsaus"))
    sauzen.items.add(Item.objects.get(name="Tomatensaus"))
    sauzen.items.add(Item.objects.get(name="Cocktailsaus"))
    sauzen.items.add(Item.objects.get(name="Joppiesaus"))
    sauzen.items.add(Item.objects.get(name="Currysaus"))
    sauzen.items.add(Item.objects.get(name="Satésaus (klein)"))
    sauzen.items.add(Item.objects.get(name="Satésaus (groot)"))


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_populatefest'),
    ]

    operations = [
        migrations.RunPython(categorise_fest)
    ]
