# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 10:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_printable_frietzonder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='days',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
