# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiebetaaltwat', '0001_initial'),
        ('orders', '0019_auto_20160925_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='wiebetaaltwat',
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wiebetaaltwat.Participant'),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentmethod',
            field=models.CharField(choices=[('participant', 'Participant'), ('bystander', 'Bystander'), ('outoflist', 'Out-of-list')], default='outoflist', max_length=11),
            preserve_default=False,
        ),
    ]
